export type UiLanguage = "ar" | "en";

/** Every text on the page, in Arabic (default) and English. The language also sets the language of the next call. */
const ar = {
  locale: "ar-SA",
  brandTagline: "لتأجير السيارات",
  demoBadge: "نسخة تجريبية",
  title: "كلّم نورة، مساعدة Budget الصوتية",
  subtitle: "اسألها عن الفروع ومواعيد العمل والأوراق المطلوبة والعروض، بلهجتك أو بالإنجليزي.",
  start: "ابدأ المكالمة",
  end: "إنهاء المكالمة",
  mute: "كتم الميكروفون",
  unmute: "تشغيل الميكروفون",
  statusIdle: "اضغط «ابدأ المكالمة» وتكلّم عادي",
  statusConnecting: "جاري الاتصال بنورة…",
  statusListening: "نورة تسمعك…",
  statusSpeaking: "نورة تتكلم…",
  statusMuted: "الميكروفون مكتوم",
  callLimit: "مدة المكالمة القصوى ١٠ دقائق",
  micError: "اسمح للمتصفح باستخدام الميكروفون عشان تكلّم نورة.",
  startError: "ما قدرنا نبدأ المكالمة. حاول مرة ثانية.",
  transcriptTitle: "نص المكالمة",
  transcriptEmpty: "كلامك وكلام نورة بيظهر هنا أثناء المكالمة.",
  you: "أنت",
  noura: "نورة",
  tryTitle: "جرّب تسأل",
  tryQuestions: [
    "وش الأوراق المطلوبة عشان أستأجر سيارة؟",
    "أبغى أقرب فرع لي في جدة، متى يفتح؟",
    "السيارة خربت في الطريق، وش أسوي؟",
    "عايز أعرف أرقام Budget في مصر",
    "What do I need to rent a car at Riyadh airport?",
  ],
  helpTitle: "نورة تساعدك في",
  help: [
    "الفروع ومواعيد العمل في ٩ دول",
    "الأوراق المطلوبة وشروط الإيجار",
    "العروض وبرنامج الولاء",
    "الأعطال والحوادث: الأرقام الصحيحة فوراً",
    "الحجوزات: قريباً في هذا العرض",
  ],
  countriesTitle: "Budget في الدول العربية",
  countries: "السعودية · الإمارات · الكويت · قطر · البحرين · عُمان · الأردن · مصر · لبنان",
  footer: "عرض تجريبي من NDI (New Digital Intelligence). ليس موقعاً رسمياً لـ Budget، والحجوزات فيه تجريبية.",
  languageLabel: "لغة المكالمة",
  lockDemo: "قفل العرض",
  signIn: "تسجيل الدخول",
  myAccount: "حسابي",
  hello: "أهلاً،",
  signUpTitle: "إنشاء حساب",
  signInTitle: "تسجيل الدخول",
  accountBenefit: "بحساب واحد، نورة تتذكّرك على الموقع وعلى الهاتف.",
  name: "الاسم",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  passwordHint: "٨ أحرف على الأقل",
  phone: "رقم الجوال (اختياري)",
  phoneHint: "عشان نورة تعرفك لما تتصل من جوالك. مثال: 05xxxxxxxx أو ‎+971…",
  submitSignUp: "إنشاء الحساب",
  submitSignIn: "دخول",
  toSignUp: "ما عندك حساب؟ أنشئ حساب",
  toSignIn: "عندك حساب؟ سجّل دخولك",
  savePhone: "حفظ الرقم",
  phoneSaved: "تم حفظ الرقم",
  signOut: "تسجيل الخروج من الحساب",
  pastCalls: "مكالماتك السابقة مع نورة",
  noCalls: "ما عندك مكالمات سابقة للحين.",
  summaryPending: "الملخص قيد التجهيز…",
  noSummary: "مكالمة قصيرة بدون ملخص",
  channelWebsite: "الموقع",
  channelPhone: "الهاتف",
  memoryOn: "نورة بتتذكّر هذه المكالمة في المرة الجاية.",
  memoryOff: "سجّل دخولك عشان نورة تتذكّر مكالماتك السابقة.",
  close: "إغلاق",
  errors: {
    name_required: "اكتب اسمك.",
    invalid_email: "البريد الإلكتروني غير صحيح.",
    weak_password: "كلمة المرور لازم تكون ٨ أحرف على الأقل.",
    invalid_phone: "رقم الجوال غير صحيح. اكتبه مع رمز الدولة، مثل ‎+966…",
    email_taken: "هذا البريد مسجّل من قبل. سجّل دخولك بدلاً من ذلك.",
    phone_taken: "هذا الرقم مسجّل في حساب ثاني.",
    wrong_credentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    unavailable: "الخدمة غير متاحة حالياً. حاول بعد شوي.",
  },
};

export type Copy = typeof ar;

const en: Copy = {
  locale: "en-GB",
  brandTagline: "Rent a Car",
  demoBadge: "Demo",
  title: "Talk to Noura, Budget's voice assistant",
  subtitle: "Ask about branches, opening hours, documents and offers, in English or in your Arabic dialect.",
  start: "Start the call",
  end: "End the call",
  mute: "Mute microphone",
  unmute: "Unmute microphone",
  statusIdle: "Press “Start the call” and just talk",
  statusConnecting: "Connecting to Noura…",
  statusListening: "Noura is listening…",
  statusSpeaking: "Noura is speaking…",
  statusMuted: "Microphone muted",
  callLimit: "Calls last up to 10 minutes",
  micError: "Please allow microphone access to talk with Noura.",
  startError: "The call could not start. Please try again.",
  transcriptTitle: "Call transcript",
  transcriptEmpty: "What you and Noura say appears here during the call.",
  you: "You",
  noura: "Noura",
  tryTitle: "Try asking",
  tryQuestions: [
    "What documents do I need to rent a car?",
    "Where is the nearest branch in Jeddah, and when does it open?",
    "My car broke down on the road. What do I do?",
    "What is the Budget Saudi loyalty programme?",
    "وش الأوراق المطلوبة عشان أستأجر سيارة؟",
  ],
  helpTitle: "Noura can help with",
  help: [
    "Branches and opening hours in 9 countries",
    "Required documents and rental rules",
    "Offers and the loyalty programme",
    "Breakdowns and accidents: the right numbers at once",
    "Reservations: coming soon in this demo",
  ],
  countriesTitle: "Budget in the Arab region",
  countries: "Saudi Arabia · UAE · Kuwait · Qatar · Bahrain · Oman · Jordan · Egypt · Lebanon",
  footer: "Demo by NDI (New Digital Intelligence). Not an official Budget website; bookings made here are demo bookings.",
  languageLabel: "Call language",
  lockDemo: "Lock the demo",
  signIn: "Sign in",
  myAccount: "My account",
  hello: "Hi,",
  signUpTitle: "Create an account",
  signInTitle: "Sign in",
  accountBenefit: "One account: Noura remembers you on the website and on the phone.",
  name: "Name",
  email: "Email",
  password: "Password",
  passwordHint: "At least 8 characters",
  phone: "Mobile number (optional)",
  phoneHint: "So Noura recognises you when you call from your phone. Example: +9665xxxxxxxx",
  submitSignUp: "Create my account",
  submitSignIn: "Sign in",
  toSignUp: "No account yet? Create one",
  toSignIn: "Already have an account? Sign in",
  savePhone: "Save number",
  phoneSaved: "Number saved",
  signOut: "Sign out of my account",
  pastCalls: "Your previous calls with Noura",
  noCalls: "No previous calls yet.",
  summaryPending: "Summary on its way…",
  noSummary: "Short call, no summary",
  channelWebsite: "Website",
  channelPhone: "Phone",
  memoryOn: "Noura will remember this call next time.",
  memoryOff: "Sign in so Noura remembers your previous calls.",
  close: "Close",
  errors: {
    name_required: "Please enter your name.",
    invalid_email: "That email address is not valid.",
    weak_password: "The password needs at least 8 characters.",
    invalid_phone: "That mobile number is not valid. Include the country code, e.g. +966…",
    email_taken: "This email already has an account. Please sign in instead.",
    phone_taken: "This number is already on another account.",
    wrong_credentials: "Wrong email or password.",
    unavailable: "The service is not available right now. Please try again shortly.",
  },
};

export const COPY: Record<UiLanguage, Copy> = { ar, en };
